# Generated by Django 4.2 on 2023-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_job',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_org',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
