# Generated by Django 4.2 on 2023-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_engineer_app', '0002_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
