# Generated by Django 4.2 on 2023-11-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_engineer_app', '0003_delete_ipaddress_user_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
