# Generated by Django 4.2 on 2023-12-01 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_engineer_app', '0005_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_engineer_app.user'),
        ),
    ]
