# Generated by Django 4.2 on 2023-12-01 04:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales_engineer_app', '0006_alter_usersession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
